# We require Nix 2.1+ for the build. "language: nix" is stuck on Nix 2.0.4, so
# we use "language: minimal" and install a more recent Nix version explicitly
# in the build script.
#
# See here for why Travis has not been updated to Nix 2.3.1:
# https://github.com/travis-ci/travis-build/pull/1804#issuecomment-550491640
language: minimal

script: |
  yes | sh <(curl https://nixos.org/releases/nix/nix-2.3.1/install) --daemon
  source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  export TMPDIR=$HOME/tmpdir
  mkdir -p "$TMPDIR"
  ./ci.sh

branches:
  only:
    - staging
    - master
    - trying

deploy:
  skip_cleanup: true
  provider: script
  script: TMPDIR=$HOME/tmpdir ./deploy.sh
  on:
    branch: master
